version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: always
    build:
      context: ./
    security_opt:
      - seccomp:unconfined
    ports:
      - 8180:8080
      - 51000:50000
    container_name: jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Asia/Seoul"
networks:
  default:
    external:
      name: jenkins-network

